version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.3"
ports: "80:80"


config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "composer update"
    - "sudo mkdir /config && sudo chmod 777 /config"


  run:
  dev:
  test:


